### ISSUE TITLE
文章列表请求适配浅色主题

### ISSUE THREAD

**Issue by ghost** [luzhenqian/vscode-juejin#5]
这是深色主题下的展示效果
![image](https://user-images.githubusercontent.com/74443578/101035294-aba4f780-35b5-11eb-9a09-c5a790b1bee6.png)

这是浅色主题下的展示效果
![image](https://user-images.githubusercontent.com/74443578/101035521-b9f31380-35b5-11eb-934a-9bca9d3bb5bb.png)

无法看到标题

**Comment by luzhenqian** [comment]
已修复。
深色主题：
![image](https://user-images.githubusercontent.com/33050549/101119263-ecd4f000-3625-11eb-9a00-bcbaa6daf633.png)
浅色主题：
![image](https://user-images.githubusercontent.com/33050549/101119198-c747e680-3625-11eb-9761-4d2019e22aa3.png)
