### ISSUE TITLE
这个插件在vscode打开不显示内容了

### ISSUE THREAD

**Issue by chen-junqiao** [luzhenqian/vscode-juejin#9]
这个插件在vscode打开不显示内容了，是不更新了吗
![image](https://user-images.githubusercontent.com/69945591/120430306-68331680-c3a9-11eb-8aaa-f3292acb3427.png)

**Comment by ihoment-chentao** [comment]
同 ，作者能回复下吗

**Comment by luzhenqian** [comment]
已修复。
